[package]
name = "multipathd-structs"
version = "0.1.1"
edition = "2024"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.25.0"
serde_json = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
