name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs['charts/prometheus-multipathd-exporter--release_created'] }}
      - uses: appany/helm-oci-chart-releaser@dd0551c15abe174eb57824ecde62e976091094da # v0.4.2
        if: ${{ steps.release.outputs['charts/prometheus-multipathd-exporter--release_created'] }}
        with:
          name: prometheus-multipathd-exporter
          repository: ${{ github.repository_owner }}
          tag: ${{ steps.release.outputs['charts/prometheus-multipathd-exporter--version'] }}
          path: charts/prometheus-multipathd-exporter
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
